### ISSUE TITLE
Bug | Auswählen von Flashlight mit Mausrad geht teilweise nicht

### ISSUE THREAD

**Issue by strukteon** [RunwayStudios/After-hours-issueboard#14]
![image](https://user-images.githubusercontent.com/16156188/149679308-f59eb116-fb11-4aac-8a6e-0c7464d592a0.png)

mit den tasten funktioniert es trotzdem

**Comment by Kdender** [comment]
passiert immer noch manchmal; hab bis zur Reception Tür gespielt, die Taschenlampe aufgehoben und nach dem load last save wieder bei der Tür wars kaputt
[Player.log](https://github.com/RunwayStudios/After-hours-issueboard/files/7888691/Player.log)

**Comment by SwipSwup** [comment]
Kanns ned nachmachen. Brauch mehr infos
