### ISSUE TITLE
Bug | dev console pops up, not closeable.

### ISSUE THREAD

**Issue by Soil1th** [RunwayStudios/After-hours-issueboard#16]
**Steps to reproduce**
Get caught by the enemy

**Current behaviour**
after i got caught the dev console popped up and a wasnt able to close it again.

**Expected behaviour**
dev console shouldnt open/ should be able to close it again

**Relevant logs and/or screenshots (optional)**
![dev_console_bug](https://user-images.githubusercontent.com/73498579/149680385-beae999f-17ef-4f8b-abb6-39c35f2779db.png)

**Comment by SwipSwup** [comment]
This development console works like intendet. The problem here is that after closing the development console another error is thrown.
