### ISSUE TITLE
Bug | map loading issue

### ISSUE THREAD

**Issue by Soil1th** [RunwayStudios/After-hours-issueboard#20]
**Steps to reproduce**
restart game and click on continue

**Current behaviour**
map is all black, only light visible, once pressed "w" you fall underground

**Expected behaviour**
map loads and you dont fall.

**Relevant logs and/or screenshots (optional)**
https://imgur.com/3J4zfLm

**Comment by fredy0002128** [comment]
Some additional Info that is similar to this issue.

When loading after you die, you the enemy doesn't work anymore and doesn't move.
If you click "load last safe" you get teleported into a corner of the map without a flashlight and you can just walk off the edge and fall into the void.

**Comment by SwipSwup** [comment]
Couldn't reproduce the exact same behaviour. Found a similar bug when dying and fixed it. Might have fixed this issues as well.
