### ISSUE TITLE
 Bug | Clipping in the dentist room, near the elevators

### ISSUE THREAD

**Issue by fredy0002128** [RunwayStudios/After-hours-issueboard#21]
You can get on top of the dentist's chair and are safe from the enemy. You can just walk onto it without problem.

**Comment by NinaMirey** [comment]
Build v0.1.1: You get stuck on the dentist's chair.



![unknown](https://user-images.githubusercontent.com/77891544/149825180-e3c8820a-465b-47e2-af0d-97928410be27.jpg)
