### ISSUE TITLE
Bug | werid clicking/stepping sound

### ISSUE THREAD

**Issue by Soil1th** [RunwayStudios/After-hours-issueboard#23]
**Steps to reproduce**
play the game

**Current behaviour**
there is a faint clicking/stepping sound every ~5 seconds.

**Relevant logs and/or screenshots (optional)**
https://imgur.com/R2Khjz0

**Comment by K0NR4D1U5** [comment]
Clip is quiet. Just turn up the volume if you listen to it

**Comment by SwipSwup** [comment]
I belive the stepping sound is coming from the flurecent light sfx. It seems to happen when the sound is looped.
