### ISSUE TITLE
Bug | Stairs are floating

### ISSUE THREAD

**Issue by Patrizzy** [RunwayStudios/After-hours-issueboard#33]
**Steps to reproduce**
Go into the cellar to the shown location.

**Current behaviour**
Stairs are floating above the ground.

**Expected behaviour**
Stairs should not float.
![image](https://user-images.githubusercontent.com/50658979/149845225-e4d778f1-7e1a-4a45-adf5-b79a472732b8.png)

**Comment by Kdender** [comment]
fixed for v0.3.0
