### ISSUE TITLE
Bug | Z-Fighting

### ISSUE THREAD

**Issue by Patrizzy** [RunwayStudios/After-hours-issueboard#35]
**Steps to reproduce**
Visit shown room on first floor.

**Current behavior**
Wall behind the wheelchair and the wall to it's right are z-fighting.

**Expected behaviour**
They should not be z-fighting.

![image](https://user-images.githubusercontent.com/50658979/149845539-2a71c345-641c-4507-96d9-422b50d6a29b.png)

**Comment by Kdender** [comment]
fixed for v0.3.0
