### ISSUE TITLE
Bug | Save Map Loading error

### ISSUE THREAD

**Issue by Zyntic** [RunwayStudios/After-hours-issueboard#41]
Steps to reproduce
go into a locker on the first floor, save and go to the main menu. After reloading the last save some map loader are not working correctly.

Current behaviour
Map loader are not working correctly.

Expected behaviour
The proper map loader should load

![image](https://user-images.githubusercontent.com/60015448/150378239-41bef74f-786b-4e34-b78c-553b07d58cd8.png)
![image](https://user-images.githubusercontent.com/60015448/150378291-030b9030-0bfc-4549-8e65-c52ea84ad901.png)
![image](https://user-images.githubusercontent.com/60015448/150378332-9ad3741e-6b66-4d4e-beb2-08121d4f5e96.png)

**Comment by Kdender** [comment]
Can't reproduce the bug, could you provide information about which locker exactly you entered?
