### ISSUE TITLE
Bug | Mapportal missplaced

### ISSUE THREAD

**Issue by SwipSwup** [RunwayStudios/After-hours-issueboard#42]
![image](https://user-images.githubusercontent.com/60540951/150407781-08b949a9-51c8-495e-908e-43fa4d89cdea.png)
![image](https://user-images.githubusercontent.com/60540951/150407893-f3a280a5-084f-48e7-af4f-cc48cede0d63.png)

**Comment by Kdender** [comment]
fixed for v0.3.0
