### ISSUE TITLE
Feature request | Storytelling & UI

### ISSUE THREAD

**Issue by timuow** [RunwayStudios/After-hours-issueboard#43]
When I first loaded up the game I was kind of confused about what was going on. Nothing indicates that you have to press e to interact with things (doors, reception desk, lockers, e.g.). The rooms should also have numbers on them to indicate that the player is going in the right direction. Why bring up the room number if the doors dont have numbers on them. 

Storytelling wise the game feels a bit lacking. For no appearent reason you are being hunted and there's nothing you can do about it. At first I didn't even know that I was being hunted. Nothing in the game indicates that someone/something is after you. I think it would be a good Idea to add a silhouette of the monster hunting you at the end of the hallway (after grabbing the flashlight and heading out.) And maybe a voiceline that indicates that you are being hunted. Something along the lines of "Huh, who was that?!" and a scream from somewhere deep in the hospital.

Maybe some form of UI help of where you should be heading to would be a good idea, or some sort of indication of where the cellar is located. It feels very frustrating to wander around aimlessly for like 10+ minutes.

I'd also like to suggest lowering the number of tapes needed to be collected and also add a very light glow effect onto them. Finding the tapes is simply a repetition of the earlier stage where you wander around aimlessly while trying to avoid the hunter doll thingy. Maybe lowering the tapes and adding another quick sidequest would be a good Idea, since you would atleast be making some kind of progess. 

Another idea I had was a heartbeat indicator that kind of tells you how far the hunter is from your current location. 

Keep up the good work :)

**Comment by K0NR4D1U5** [comment]
My brother also didnt know where the basement is located. He expected it to be connected somewhere in the hallway and only after 10 minutes started looking into rooms accidentally finding the staircase leading to the basement.

**Comment by K0NR4D1U5** [comment]
Heart beat is done
