### ISSUE TITLE
Feature Request | Better Visibility in Lockers

### ISSUE THREAD

**Issue by Kdender** [RunwayStudios/After-hours-issueboard#6]
Make the gaps wider to allow the player to see more of what's going on in the middle.

![image](https://user-images.githubusercontent.com/51720989/149090051-a7a8e814-5150-4ceb-a7c6-4fac2e1914eb.png)

**Comment by K0NR4D1U5** [comment]
In a way we want to limit the amount of information a player can get in a horror game but making those holes more centered would make sense
