### ISSUE TITLE
Feature Request | Enemy footsteps and proximity heartbeat

### ISSUE THREAD

**Issue by Patrizzy** [RunwayStudios/After-hours-issueboard#62]
Footsteps the enemy makes so you can hear her from further away and walking through the building and a proximity based heartbeat sound where the heart beats faster the closer the enemy gets to the player so you can better tell if she's going away or coming closer.

**Comment by K0NR4D1U5** [comment]
Heartbeat already described in Issue #43

**Comment by K0NR4D1U5** [comment]
Will either do Highheel Steps, Barefoot Steps or even Idle Sounds instead

**Comment by K0NR4D1U5** [comment]
Added heartbeat, footsteps are replaced with String Ambience
