### ISSUE TITLE
Bug | Locker Clipping Into Wall

### ISSUE THREAD

**Issue by Kdender** [RunwayStudios/After-hours-issueboard#7]
**Steps to reproduce**
Go to the first floor and find locker shown in screenshot

**Current behaviour**
The wall is visible from the inside of the locker

**Expected behaviour**
The other walls shouldn't clip into the locker

![image](https://user-images.githubusercontent.com/51720989/149096617-f522b160-8a84-4399-89e5-e5d98a95dc6e.png)

**Comment by Patrizzy** [comment]
👎🏻

**Comment by K0NR4D1U5** [comment]
closed?
