### ISSUE TITLE
Bug | Two guidepoints

### ISSUE THREAD

**Issue by NinaMirey** [RunwayStudios/After-hours-issueboard#75]
**Steps to reproduce:**

Go to the reception -> die in the basement -> reload the last savepoint

![image](https://user-images.githubusercontent.com/77891544/151525857-5a8acc57-12d8-4b90-a768-0d9a761c9c84.png)

And they shift to another place when you come near them

![image](https://user-images.githubusercontent.com/77891544/151526576-f54dd7e6-beea-4dd9-962e-3f39a701a176.png)

**Comment by Kdender** [comment]
As far as I know, this was intended. Although it does feel pretty unintuitive, we should probably place only one icon in one of the staircases and place it going down the stairs, not at the entrance.

**Comment by K0NR4D1U5** [comment]
Id keep it at the entrance however maybe only show the nearest of both at all times

**Comment by Kdender** [comment]
there are 2 extra guidepoints guiding you down to the basement
