### ISSUE TITLE
Feature request | Audio Source following the player

### ISSUE THREAD

**Issue by K0NR4D1U5** [RunwayStudios/After-hours-issueboard#82]
Add an audiosource that follows the player and rotation in the position the flashlight is presumed to be to be able to build in flashlight flickering audibly coming from it and being able to attach reverb to the sound relative to the surrounding.

**Comment by Kdender** [comment]
![image](https://user-images.githubusercontent.com/51720989/151711907-6d91c5cd-4f4f-4183-9108-c8663bce02e5.png)
already exists, set the flashlight as the gameObject and the sound will follow the flashlight
