### ISSUE TITLE
Bug build 0.4.4 | screen resolution downgrade

### ISSUE THREAD

**Issue by NinaMirey** [RunwayStudios/After-hours-issueboard#86]
_Steps to recreate_

I lowered the audio volume and suddenly the screen resolution downgraded. 

![image](https://user-images.githubusercontent.com/77891544/152468473-cec3374c-a6c3-432c-aeeb-51a2ce87de6a.png)

Turning the audio volume back on and selecting a higher resolution triggered exceptions. 

![image](https://user-images.githubusercontent.com/77891544/152468488-c92377bc-7d64-41ed-a944-424014389703.png)
![image](https://user-images.githubusercontent.com/77891544/152468658-fc9651eb-c855-4317-bedb-2d8ce97091a5.png)

[Player.log](https://github.com/RunwayStudios/After-hours-issueboard/files/7999897/Player.log)

**Comment by NinaMirey** [comment]
[Saves.zip](https://github.com/RunwayStudios/After-hours-issueboard/files/8003288/Saves.zip)

**Comment by Kdender** [comment]
fixed in future version ^^
